services:
  postgres:
    image: postgres:15-alpine
    container_name: 3j_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 3j_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 3j_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: 3j_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - 3j_network

volumes:
  postgres_data:

networks:
  3j_network:
    driver: bridge
